name = "IPTFreedom"
mc_version = "1.19.4"

[jar]
type = "url"
url = "https://ci.plex.us.org/job/Scissors/job/1.19.4/50/artifact/build/libs/scissors-1.19.4-50.jar"

[variables]
SERVER_ADDRESS = "ipt.esixtwo.one"
PORT = "25565"
TELNET_PORT = "25765"

# Don't change these if you're running on docker
DATABASE_HOST = "database"
DATABASE_PORT = "3306"
DATABASE_USER = "root"

DATABASE_PASS = "XTiMm5LkPACxyjJ4bXm5wXsFmHTwYDNY"
DATABASE_NAME = "iptfreedom"

OWNERS = "maniaplay"
EXECUTIVES = "G6_"
ASSISTANT_EXECUTIVES = ""

DISCORD_INVITE = "https://discord.com/invite/iptfreedom"
DISCORD_TOKEN = ""
DISCORD_PREFIX = "ipt!"
DISCORD_SERVER_ID = ""
DISCORD_CHANNEL_ID_CHAT = ""
DISCORD_CHANNEL_ID_ADMIN = ""
DISCORD_ROLE_ID_MASTER_BUILDER = ""
DISCORD_ROLE_ID_ADMIN = ""
DISCORD_ROLE_ID_SENIOR_ADMIN = ""
DISCORD_ROLE_ID_DEVELOPER = ""
DISCORD_ROLE_ID_ASSISTANT_EXECUTIVE = ""
DISCORD_ROLE_ID_EXECUTIVE = ""
DISCORD_ROLE_ID_SERVER_OWNER = ""

[launcher]
aikars_flags = true
proxy_flags = false
eula_args = true
nogui = true

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/TotalFreedomMod/releases/download/2022.06.03-IPT/TotalFreedomMod-2022.06.3-IPT.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/Minecraft-JDA/releases/download/5.0.0-beta.10-1/Minecraft-JDA-5.0.0-beta.10-1.jar"

[[plugins]]
type = "url"
url = "https://ci.enginehub.org/repository/download/bt11/22021:id/worldguard-bukkit-7.0.9-SNAPSHOT-dist.jar?branch=version/7.0.x&guest=1"

[[plugins]]
type = "url"
url = "https://ci.plex.us.org/job/FastAsynchronousIncompetence/27/artifact/worldedit-bukkit/build/libs/FastAsyncWorldEdit-Bukkit-2.6.2-SNAPSHOT-27.jar"

[[plugins]]
type = "modrinth"
id = "buildersutilities"
version = "usc9dcSx"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/BukkitTelnet/releases/download/4.9-IPT/BukkitTelnet.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/Addendum/releases/download/1.0.0/Addendum-1.0.0.jar"

[[plugins]]
type = "spigot"
id = "carz.56255"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/ESP/releases/download/1.1/ESP-1.1.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/TF-EssentialsX/releases/download/2.20.1/EssentialsX-2.20.1-dev+395-92d7f94.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/TF-EssentialsX/releases/download/2.20.1/EssentialsXSpawn-2.20.1-dev+395-92d7f94.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/EmotesTF/releases/download/1.0/EmotesTF.jar"

# TODO: Decompile this one and clean up the code & make a release
[[plugins]]
type = "url"
url = "https://cdn.discordapp.com/attachments/1041011669872160769/1116508640480874556/CrackShot-0.99.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/MarriageMaster/releases/download/2.7.0.2-IPT/MarriageMaster-2.7.0.2-IPT.jar"

[[plugins]]
type = "url"
url = "https://ci.pcgamingfreaks.at/job/PluginLib/lastSuccessfulBuild/artifact/target/PCGF_PluginLib-1.0.39-SNAPSHOT.jar"

[[plugins]]
type = "url"
url = "https://github.com/Focusvity/ItemizerX/releases/download/1.8/ItemizerX.jar"

[[plugins]]
type = "modrinth"
id = "coreprotect"
version = "mvLpRWww"

[[plugins]]
type = "url"
url = "https://github.com/ViaVersion/ViaVersion/releases/download/4.7.0/ViaVersion-4.7.0.jar"

[[plugins]]
type = "url"
url = "https://github.com/ViaVersion/ViaBackwards/releases/download/4.7.0/ViaBackwards-4.7.0.jar"

[[plugins]]
type = "url"
url = "https://github.com/Jikoo/OpenInv/releases/download/4.3.0/OpenInv.jar"

[[plugins]]
type = "url"
url = "https://github.com/IPTFreedom/PlotSquared/releases/download/6.11.2-IPT/PlotSquared-Bukkit-6.11.2-IPT.jar"

[[plugins]]
type = "url"
url = "https://github.com/Gecolay/GSit/releases/download/1.4.5/GSit-1.4.5.jar"

[[plugins]]
type = "url"
url = "https://ci.codemc.io/job/filoghost/job/HolographicDisplays/lastSuccessfulBuild/artifact/HolographicDisplays-3.0.3-SNAPSHOT.jar"

[[plugins]]
type = "url"
url = "https://github.com/kikelkik/LiftReloaded/releases/download/2.4.2/lift-reloaded-2.4.2.jar"

[[plugins]]
type = "url"
url = "https://github.com/aromaa/WorldGuardExtraFlags/releases/download/v4.2.1/WorldGuardExtraFlags.jar"
