name = "iptfreedom"
mc_version = "1.19.4"

[jar]
type = "url"
url = "https://ci.plex.us.org/job/Scissors/job/1.19.4/46/artifact/build/libs/scissors-46.jar"

[variables]
PORT = "25565"

[launcher]
aikars_flags = true
proxy_flags = false
eula_args = true
nogui = true
