name = "IPTFreedom"
mc_version = "1.20.1"

[jar]
type = "jenkins"
url = "https://ci.plex.us.org"
job = "Scissors/1.20.1"
build = "latest"
artifact = "first"

[variables]
SERVER_ADDRESS = "ipt.esixtwo.one"
PORT = "25565"
TELNET_PORT = "25765"

# Don't change these if you're running on docker
DATABASE_HOST = "database"
DATABASE_PORT = "3306"
DATABASE_USER = "root"

DATABASE_PASS = "XTiMm5LkPACxyjJ4bXm5wXsFmHTwYDNY"
DATABASE_NAME = "iptfreedom"

OWNERS = "maniaplay"
EXECUTIVES = "G6_"
ASSISTANT_EXECUTIVES = ""

DISCORD_INVITE = "https://discord.com/invite/iptfreedom"
DISCORD_TOKEN = ""
DISCORD_PREFIX = "ipt!"
DISCORD_SERVER_ID = ""
DISCORD_CHANNEL_ID_CHAT = ""
DISCORD_CHANNEL_ID_ADMIN = ""
DISCORD_ROLE_ID_MASTER_BUILDER = ""
DISCORD_ROLE_ID_ADMIN = ""
DISCORD_ROLE_ID_SENIOR_ADMIN = ""
DISCORD_ROLE_ID_DEVELOPER = ""
DISCORD_ROLE_ID_ASSISTANT_EXECUTIVE = ""
DISCORD_ROLE_ID_EXECUTIVE = ""
DISCORD_ROLE_ID_SERVER_OWNER = ""

[launcher]
jvm_args = "-XX:+ExitOnOutOfMemoryError"
aikars_flags = true
eula_args = true
nogui = true
memory = "6500M"

[launcher.properties]
"com.github.iptfreedom.fastasynchronousincompetence.allowv7" = "true"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/TotalFreedomMod"
tag = "2022.06.08-IPT"
asset = "TotalFreedomMod"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/Minecraft-JDA"
tag = "5.0.0-beta.10-1"
asset = "Minecraft-JDA"

[[plugins]]
type = "url"
url = "https://ci.enginehub.org/repository/download/bt11/22205:id/worldguard-bukkit-7.0.9-SNAPSHOT-dist.jar?branch=version/7.0.x&guest=1"
filename = "worldguard-bukkit-7.0.9-SNAPSHOT-dist.jar"
desc = "WorldGuard"

[[plugins]]
type = "jenkins"
url = "https://ci.plex.us.org"
job = "FastAsynchronousIncompetence"
build = "latest"
artifact = "first"

[[plugins]]
type = "modrinth"
id = "buildersutilities"
version = "usc9dcSx"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/BukkitTelnet"
tag = "4.9.3-IPT"
asset = "bukkittelnet"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/Addendum"
tag = "1.0.0"
asset = "Addendum"

[[plugins]]
type = "spigot"
id = "carz.56255"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/ESP"
tag = "1.1"
asset = "ESP"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/TF-EssentialsX"
tag = "2.20.1"
asset = "EssentialsX"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/TF-EssentialsX"
tag = "2.20.1"
asset = "EssentialsXSpawn"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/EmotesTF"
tag = "1.1"
asset = "emotestf"

# TODO: Decompile this one and clean up the code & make a release
[[plugins]]
type = "url"
url = "https://cdn.discordapp.com/attachments/1041011669872160769/1116508640480874556/CrackShot-0.99.jar"
filename = "CrackShot-0.99.jar"
desc = "TODO: Decompile this one and clean up the code & make a release"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/MarriageMaster"
tag = "2.7.0.2-IPT"
asset = "MarriageMaster"

[[plugins]]
type = "jenkins"
url = "https://ci.pcgamingfreaks.at"
job = "PluginLib"
build = "latest"
artifact = "first"

# TODO(mcman): change when hangar support
[[plugins]]
type = "url"
url = "https://hangarcdn.papermc.io/plugins/Telesphoreo/ItemizerX/versions/2.0/PAPER/ItemizerX.jar"
filename = "ItemizerX.jar"
desc = "TODO(mcman): change when hangar support"

[[plugins]]
type = "modrinth"
id = "coreprotect"
version = "mvLpRWww"

[[plugins]]
type = "ghrel"
repo = "ViaVersion/ViaVersion"
tag = "4.7.0"
asset = "ViaVersion"

[[plugins]]
type = "ghrel"
repo = "ViaVersion/ViaBackwards"
tag = "4.7.0"
asset = "ViaBackwards"

[[plugins]]
type = "ghrel"
repo = "Jikoo/OpenInv"
tag = "4.3.1"
asset = "OpenInv.jar"

[[plugins]]
type = "ghrel"
repo = "IPTFreedom/PlotSquared"
tag = "7.0.0-beta.3-IPT"
asset = "plotsquared-bukkit"

[[plugins]]
type = "ghrel"
repo = "Gecolay/GSit"
tag = "1.4.7"
asset = "GSit"

[[plugins]]
type = "jenkins"
url = "https://ci.codemc.io"
job = "filoghost/HolographicDisplays"
build = "latest"
artifact = "first"

[[plugins]]
type = "ghrel"
repo = "kikelkik/LiftReloaded"
tag = "2.4.3"
asset = "lift-reloaded"

[[plugins]]
type = "ghrel"
repo = "aromaa/WorldGuardExtraFlags"
tag = "v4.2.1"
asset = "WorldGuardExtraFlags.jar"

[[plugins]]
type = "jenkins"
url = "https://ci.md-5.net"
job = "LibsDisguises"
build = "latest"
artifact = "first"

[[plugins]]
type = "ghrel"
repo = "ayunami2000/LiberalDisguises"
tag = "v1.0.0"
asset = "liberaldisguises"

[[plugins]]
type = "jenkins"
url = "https://ci.dmulloy2.net"
job = "ProtocolLib"
build = "latest"
artifact = "first"

[[plugins]]
type = "jenkins"
url = "https://ci.lucko.me"
job = "spark"
build = "latest"
artifact = "bukkit"

[markdown]
files = [
    "README.md",
    "PLUGINS.md"
]
auto_update = false
